export const TABLES_MAP = {
    "11": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 1, tableName: "Oishi", tableType: "bàn tròn" },
    "12": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 2, tableName: "Lutos", tableType: "bàn tròn" },
    "13": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 3, tableName: "London", tableType: "bàn tròn" },
    "14": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 4, tableName: "Fuji", tableType: "bàn dài" },
    "15": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 5, tableName: "Sugoi", tableType: "bàn dài" },
    "16": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 6, tableName: "Chicago", tableType: "bàn tròn" },
    "17": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 7, tableName: "Monaco", tableType: "bàn tròn" },
    "18": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 8, tableName: "Lyon", tableType: "bàn dài" },
    "19": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 9, tableName: "Dubai", tableType: "bàn dài" },
    "110": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 10, tableName: "Pharaod", tableType: "bàn tròn" },

    "21": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 1, tableName: "Oishi", tableType: "bàn tròn" },
    "22": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 2, tableName: "Lutos", tableType: "bàn tròn" },
    "23": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 3, tableName: "London", tableType: "bàn tròn" },
    "24": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 4, tableName: "Fuji", tableType: "bàn dài" },
    "25": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 5, tableName: "Sugoi", tableType: "bàn dài" },
    "26": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 6, tableName: "Chicago", tableType: "bàn tròn" },
    "27": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 7, tableName: "Monaco", tableType: "bàn tròn" },
    "28": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 8, tableName: "Lyon", tableType: "bàn dài" },
    "29": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 9, tableName: "Dubai", tableType: "bàn dài" },
    "210": { branchId: 2, branchName: "Gold One 2", branchAddress: "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", tableId: 10, tableName: "Pharaod", tableType: "bàn tròn" },

    "31": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 1, tableName: "Oishi", tableType: "bàn tròn" },
    "32": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 2, tableName: "Lutos", tableType: "bàn tròn" },
    "33": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 3, tableName: "London", tableType: "bàn tròn" },
    "34": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 4, tableName: "Fuji", tableType: "bàn dài" },
    "35": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 5, tableName: "Sugoi", tableType: "bàn dài" },
    "36": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 6, tableName: "Chicago", tableType: "bàn tròn" },
    "37": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 7, tableName: "Monaco", tableType: "bàn tròn" },
    "38": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 8, tableName: "Lyon", tableType: "bàn dài" },
    "39": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 9, tableName: "Dubai", tableType: "bàn dài" },
    "310": { branchId: 3, branchName: "Gold One 3", branchAddress: "Số 10, Đường Alexander De Rhodes, Quận 1, TP.HCM", tableId: 10, tableName: "Pharaod", tableType: "bàn tròn" }
};
