export const TABLES_MAP = {
    "11": { branchId: 1, branchName: "Gold One 1", branchAddress: "258-260 Đường Phan Xích Long, Quận Phú Nhuận", tableId: 1, tableName: "Trống", tableType: "bàn nhỏ" },

    "211": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 11, "tableName": "DIAMOND", "tableType": "bàn dài" },
    "212": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 12, "tableName": "RUBY", "tableType": "bàn dài" },
    "213": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 13, "tableName": "GEMIS", "tableType": "bàn dài" },
    "214": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 14, "tableName": "PHƯỚC LỘC THỌ", "tableType": "bàn dài" },
    "215": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 15, "tableName": "HY LẠP", "tableType": "bàn tròn" },
    "216": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 16, "tableName": "HÀ LAN", "tableType": "bàn tròn" },
    "217": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 17, "tableName": "HAPPY", "tableType": "bàn dài" },
    "218": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 18, "tableName": "CRYSTAL", "tableType": "bàn dài" },
    "219": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 19, "tableName": "ROMANTIC", "tableType": "bàn dài" },
    "220": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 20, "tableName": "FAMILY", "tableType": "bàn dài" },
    "221": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 21, "tableName": "SAPPHIRE", "tableType": "bàn tròn" },
    "222": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 22, "tableName": "AI CẬP", "tableType": "bàn tròn" },
    "223": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 23, "tableName": "GOLD", "tableType": "bàn dài" },
    "224": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 24, "tableName": "ROYAL", "tableType": "bàn dài" },
    "225": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 25, "tableName": "PLATINUM", "tableType": "bàn dài" },
    "226": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 26, "tableName": "LUXURIOUS", "tableType": "bàn dài" },
    "227": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 27, "tableName": "PARIS", "tableType": "bàn dài" },
    "228": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 28, "tableName": "CANADA", "tableType": "bàn dài" },
    "229": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 29, "tableName": "JAPAN", "tableType": "bàn dài" },
    "230": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 30, "tableName": "VIP 3", "tableType": "bàn dài" },
    "231": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 31, "tableName": "VIP 15", "tableType": "bàn dài" },
    "232": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 32, "tableName": "VIP 16", "tableType": "bàn dài" },
    "233": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 33, "tableName": "VIP 17", "tableType": "bàn dài" },
    "234": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 34, "tableName": "VIP 18", "tableType": "bàn dài" },
    "235": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 35, "tableName": "VIP 19", "tableType": "bàn dài" },
    "236": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 36, "tableName": "VIP 20", "tableType": "bàn dài" },
    "237": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 37, "tableName": "VIP 21", "tableType": "bàn dài" },
    "238": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 38, "tableName": "VIP 22", "tableType": "bàn dài" },
    "239": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 39, "tableName": "CAIRO", "tableType": "bàn tròn" },
    "240": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 40, "tableName": "KOBE", "tableType": "bàn dài" },
    "241": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 41, "tableName": "TOKYO", "tableType": "bàn dài" },
    "242": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 42, "tableName": "HIROSHIMA", "tableType": "bàn dài" },
    "243": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 43, "tableName": "YOKOHAMA", "tableType": "bàn dài" },
    "244": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 44, "tableName": "OSAKA", "tableType": "bàn dài" },
    "245": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 45, "tableName": "NAGOYA", "tableType": "bàn dài" },
    "246": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 46, "tableName": "SAPPORO", "tableType": "bàn dài" },
    "247": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 47, "tableName": "HOKKAIDO", "tableType": "bàn dài" },
    "248": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 48, "tableName": "KYOTO", "tableType": "bàn dài" },
    "249": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 49, "tableName": "MEXICO", "tableType": "bàn dài" },
    "250": { "branchId": 2, "branchName": "Gold One 2", "branchAddress": "41-41A-43 Nguyễn Thị Diệu, Phường 6, Quận 3", "tableId": 50, "tableName": "WORLD", "tableType": "bàn dài" },

    "311": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 1,  "tableName": "OISHI",       "tableType": "bàn tròn" },
    "312": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 2,  "tableName": "HAKKI",       "tableType": "bàn tròn" },
    "313": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 3,  "tableName": "KOI",         "tableType": "bàn tròn" },
    "314": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 4,  "tableName": "SYDNEY",      "tableType": "bàn tròn" },
    "315": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 5,  "tableName": "NEW ZEALAND", "tableType": "bàn tròn" },
    "316": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 6,  "tableName": "KIMONO",      "tableType": "bàn dài" },
    "317": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 7,  "tableName": "LOTUS",       "tableType": "bàn tròn" },
    "318": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 8,  "tableName": "YURI",        "tableType": "bàn tròn" },
    "319": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 9,  "tableName": "SAKURA",      "tableType": "bàn dài" },
    "320": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 10, "tableName": "FUJI",        "tableType": "bàn dài" },
    "321": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 11, "tableName": "SUGOI",       "tableType": "bàn dài" },
    "322": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 12, "tableName": "CHICAGO",     "tableType": "bàn tròn" },
    "323": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 13, "tableName": "PHARAOH",     "tableType": "bàn tròn" },
    "324": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 14, "tableName": "LONDON",      "tableType": "bàn tròn" },
    "325": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 15, "tableName": "MONACO",      "tableType": "bàn tròn" },
    "326": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 16, "tableName": "LYON",        "tableType": "bàn dài" },
    "327": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 17, "tableName": "DUBAI",       "tableType": "bàn dài" },
    "328": { "branchId": 3, "branchName": "Gold One 3", "branchAddress": "Số 10, Đường Alexander De Rhodes, Quận 1", "tableId": 18, "tableName": "VIP 1",       "tableType": "bàn dài" },
};
